global:
  sendAnonymousUsage: false
  checkNewVersion: false

api:
  dashboard: true
  debug: true

entryPoints:
  web:
    address: ":80"
    asDefault: true
  
  ping:
    address: ":8082"

providers:
  # File provider for dynamic configuration
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

  # Docker provider
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik
    watch: true

# Logging
log:
  level: INFO
  filePath: /data/logs/traefik.log
  format: json
  
accessLog:
  filePath: /data/logs/access.log
  format: json
  filters:
    statusCodes:
      - "400-499"
      - "500-599"
  fields:
    headers:
      defaultMode: drop # drop all headers per default
      names:
          User-Agent: keep # log user agent strings

# Ping for health checks
ping:
  entryPoint: ping