networks:
  traefik:
    external: true

services:
  minio:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - /mnt/storage:/srv/storage
      - /home/amjad:/srv/amjad_home
      - /mnt/storage/filebrowser/database:/database
      - /mnt/storage/filebrowser/config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      FB_NOAUTH: "true"
    labels:
      # Enable Traefik
      - "traefik.enable=true"

      - "traefik.http.routers.filebrowser.rule=Host(`filebrowser.home.alsharafi.dev`)"
      - "traefik.http.routers.filebrowser.service=filebrowser"
      - "traefik.http.routers.filebrowser.middlewares=default-chain@file"
      - "traefik.http.services.filebrowser.loadbalancer.server.port=80"
    user: "1000:1000"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:80"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
