networks:
  traefik:
    name: traefik
    driver: bridge

volumes:
  letsencrypt:

secrets:
  cloudflare-email:
    file: /run/secrets/cloudflare-email
  cloudflare-dns-api-token:
    file: /run/secrets/cloudflare-dns-api-token
  cloudflare-zone-api-token:
    file: /run/secrets/cloudflare-zone-api-token

services:
  traefik:
    image: traefik:v3
    container_name: traefik
    restart: unless-stopped
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log/traefik:/data/logs
      - letsencrypt:/letsencrypt
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/dynamic.yml:/etc/traefik/dynamic.yml:ro
    secrets:
      - cloudflare-email
      - cloudflare-dns-api-token
      - cloudflare-zone-api-token
    environment:
      - CLOUDFLARE_EMAIL_FILE=/run/secrets/cloudflare-email
      - CLOUDFLARE_DNS_API_TOKEN_FILE=/run/secrets/cloudflare-dns-api-token
      - CLOUDFLARE_ZONE_API_TOKEN_FILE=/run/secrets/cloudflare-zone-api-token
    labels:
      # Dashboard
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.home.amsh.dev`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=default-chain@file,oauth2-auth@docker"
    extra_hosts:
      - "host.docker.internal:127.0.0.1"
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 30s
      timeout: 5s
      retries: 3
  debug-server:
    image: traefik/whoami
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.debug.rule=Host(`debug.home.amsh.dev`)"
      - "traefik.http.services.debug.loadbalancer.server.port=80"
      - "traefik.http.routers.debug.middlewares=default-chain@file"
