networks:
  traefik:
    external: true

services:
  # Dockege - Docker Engine GUI
  dockge:
    container_name: dockge
    image: louislam/dockge:1
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /storage/dockge/data:/app/data
      - /opt/docker-services/:/opt/docker-services/:ro
      - /var/lib/dock:/var/lib/dock:ro
      - /run/secrets/rendered:/run/secrets/rendered:ro
    environment:
      - DOCKGE_STACKS_DIR=/opt/docker-services/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dockge.rule=Host(`dockge.home.amsh.dev`)"
      - "traefik.http.services.dockge.loadbalancer.server.port=5001"
      - "traefik.http.routers.dockge.middlewares=default-chain@file,oauth2-auth@docker"
    extra_hosts:
      - "home.server:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:5001"]
      interval: 30s
      timeout: 10s
      retries: 3
