#!/usr/bin/env bash
# backup-postgres — dump all postgres DBs for a backup group into DUMP_DIR.
# Called by the restic backupPrepareCommand generated by service-registry.nix.
#
# Required env: DUMP_DIR, GROUP_NAME
# Arg $1: JSON array of postgres entries

set -euo pipefail

source /etc/homelab/lib.sh

for v in DUMP_DIR GROUP_NAME; do
  require_env "$v"
done

mkdir -p "$DUMP_DIR"

# Accept JSON array as first arg or stdin
pg_json="${1:-$(cat)}"

failed=0
total=0
entries=()
mapfile -t entries < <(echo "$pg_json" | jq -c '.[]')

for entry in "${entries[@]}"; do
  stack=$(jq_field "$entry" stack)
  compose_svc=$(jq_field "$entry" composeService)
  database=$(jq_field "$entry" database)
  user=$(jq_field "$entry" user)
  dump_file="${DUMP_DIR}/${database}.sql"

  total=$((total + 1))
  log "[${GROUP_NAME}] Dumping ${database} from ${stack}/${compose_svc}..."

  compose-manage start-container "$stack" "$compose_svc" >/dev/null

  ready=0
  for _ in $(seq 1 30); do
    if compose-manage exec -T "$stack" "$compose_svc" pg_isready -U "$user" -q 2>/dev/null; then
      ready=1
      break
    fi
    sleep 1
  done
  if (( ready == 0 )); then
    log_err "[${GROUP_NAME}] Postgres not ready in ${stack}/${compose_svc} after 30s — skipping dump of ${database}"
    failed=$((failed + 1))
    continue
  fi

  dump_rc=0
  compose-manage exec -T "$stack" "$compose_svc" pg_dump -U "$user" "$database" > "$dump_file" || dump_rc=$?
  if (( dump_rc != 0 )); then
    log_err "[${GROUP_NAME}] pg_dump failed for ${database} (exit ${dump_rc})"
    rm -f "$dump_file"
    failed=$((failed + 1))
    continue
  fi

  log_ok "[${GROUP_NAME}] Dumped ${database} → ${dump_file} ($(du -sh "$dump_file" | cut -f1))"
done

if (( failed > 0 )); then
  log_err "[${GROUP_NAME}] ${failed}/${total} postgres dumps failed — aborting backup"
  exit 1
fi

log "[${GROUP_NAME}] All ${total} postgres dump(s) complete."
