#!/usr/bin/env bash
# backup-sqlite — produce a consistent VACUUM INTO copy of each SQLite DB for a
# backup group into DUMP_DIR. Called by the restic backupPrepareCommand
# generated by service-registry.nix.
#
# The live DB file (and its -wal/-shm sidecars) are still backed up raw via the
# service's backup.paths; this copy is an additional guaranteed-consistent
# artifact captured in every snapshot. Restore restores the raw file as-is —
# this copy is a manual recovery fallback if the raw file is torn.
#
# Required env: DUMP_DIR, GROUP_NAME
# Arg $1: JSON array of sqlite entries: [{ name, path }]

set -euo pipefail

source /etc/homelab/lib.sh

for v in DUMP_DIR GROUP_NAME; do
  require_env "$v"
done

mkdir -p "$DUMP_DIR"

# Accept JSON array as first arg or stdin
db_json="${1:-$(cat)}"

failed=0
total=0
entries=()
mapfile -t entries < <(echo "$db_json" | jq -c '.[]')

for entry in "${entries[@]}"; do
  name=$(jq_field "$entry" name)
  path=$(jq_field "$entry" path)
  # name is a collision-free, path-derived slug computed in service-registry.nix;
  # written verbatim (it has no extension appended by us).
  dest="${DUMP_DIR}/${name}.db"

  total=$((total + 1))
  log "[${GROUP_NAME}] Vacuuming sqlite ${name} from ${path}..."

  if [[ ! -f $path ]]; then
    log_err "[${GROUP_NAME}] SQLite file not found: ${path} — skipping ${name}"
    failed=$((failed + 1))
    continue
  fi

  # VACUUM INTO requires the destination not to exist.
  rm -f "$dest"

  vac_rc=0
  sqlite3 "$path" "VACUUM INTO '${dest}'" || vac_rc=$?
  if (( vac_rc != 0 )); then
    log_err "[${GROUP_NAME}] VACUUM INTO failed for ${name} (exit ${vac_rc})"
    rm -f "$dest"
    failed=$((failed + 1))
    continue
  fi

  log_ok "[${GROUP_NAME}] Vacuumed ${name} → ${dest} ($(du -sh "$dest" | cut -f1))"
done

if (( failed > 0 )); then
  log_err "[${GROUP_NAME}] ${failed}/${total} sqlite vacuum(s) failed — aborting backup"
  exit 1
fi

log "[${GROUP_NAME}] All ${total} sqlite vacuum(s) complete."
