#!/usr/bin/env bash
# homelab-backup-postgres — dump all postgres DBs for a backup group into DUMP_DIR.
# Called by the restic backupPrepareCommand generated by service-registry.nix.
#
# Required env:
#   DUMP_DIR    — directory to write .sql files into
#   GROUP_NAME  — backup group name (for log prefixes)
#
# Positional args: JSON array of postgres entries, one per line, each as:
#   {"container":"...","composeService":"...","database":"...","user":"..."}
# Passed via stdin or as $1 (JSON string).

set -euo pipefail

: "${DUMP_DIR:?DUMP_DIR not set}"
: "${GROUP_NAME:?GROUP_NAME not set}"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
log()  { echo -e "${BLUE}[$(date -Iseconds)] [${GROUP_NAME}]${NC} $*"; }
ok()   { echo -e "${GREEN}✓${NC} $*"; }
err()  { echo -e "${RED}✗${NC} $*" >&2; }

mkdir -p "$DUMP_DIR"

# Accept JSON array as first arg or stdin
pg_json="${1:-$(cat)}"

failed=0
total=0

while IFS= read -r entry; do
  container=$(echo "$entry" | jq -r '.container')
  database=$(echo "$entry"  | jq -r '.database')
  user=$(echo "$entry"      | jq -r '.user')
  dump_file="${DUMP_DIR}/${database}.sql"

  total=$((total + 1))
  log "Dumping ${database} from ${container}..."

  if ! docker inspect "$container" >/dev/null 2>&1; then
    err "[${GROUP_NAME}] Container ${container} not found — skipping dump of ${database}"
    failed=$((failed + 1))
    continue
  fi

  if ! docker exec "$container" pg_isready -U "$user" -d "$database" -q 2>/dev/null; then
    err "[${GROUP_NAME}] Postgres not ready in ${container} — skipping dump of ${database}"
    failed=$((failed + 1))
    continue
  fi

  dump_rc=0
  docker exec "$container" pg_dump -U "$user" "$database" > "$dump_file" || dump_rc=$?
  if (( dump_rc != 0 )); then
    err "[${GROUP_NAME}] pg_dump failed for ${database} (exit ${dump_rc})"
    rm -f "$dump_file"
    failed=$((failed + 1))
    continue
  fi

  ok "[${GROUP_NAME}] Dumped ${database} → ${dump_file} ($(du -sh "$dump_file" | cut -f1))"
done < <(echo "$pg_json" | jq -c '.[]')

if (( failed > 0 )); then
  err "[${GROUP_NAME}] ${failed}/${total} postgres dumps failed — aborting backup"
  exit 1
fi

log "All ${total} postgres dump(s) complete."
