networks:
  traefik:
    external: true

services:
  dashy:
    image: lissy93/dashy:latest
    container_name: dashy
    restart: unless-stopped
    volumes:
      - ./conf.yml:/app/user-data/conf.yml
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashy.rule=Host(`home.amsh.dev`)"
      - "traefik.http.services.dashy.loadbalancer.server.port=8080"
      - "traefik.http.routers.dashy.middlewares=default-chain@file"
    networks:
      - traefik
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 30s
      timeout: 5s
      retries: 3