
networks:
  traefik:
    external: true

services:
  upsnap:
    container_name: upsnap
    build: .
    network_mode: host
    restart: unless-stopped
    volumes:
      - /mnt/storage/upsnap:/app/pb_data
    user: 1000:1000
    cap_add:
      - CAP_NET_RAW
    environment:
      TZ: "Asia/Kuala_Lumpur"
      UPSNAP_PING_PRIVILEGED: false
      UPSNAP_SCAN_RANGE: "192.168.0.0/24"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.upsnap.rule=Host(`upsnap.home.amsh.dev`)"
      - "traefik.http.routers.upsnap.middlewares=default-chain@file"
      - "traefik.http.services.upsnap.loadbalancer.server.url=http://host.docker.internal:8090"
    healthcheck:
      test: ["CMD", "curl", "-fs", "http://localhost:8090/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
